### ISSUE TITLE
Some of  the image url seems to be broken

### ISSUE THREAD

**Issue by twentyse7en** [vasanthk/how-web-works#21]
![image](https://user-images.githubusercontent.com/59721339/179357505-1ae3f0f9-e373-44c9-8781-4539177999a0.png)

**Comment by zhalice2011** [comment]
I also have this problem

**Comment by jiujiujiujiujiuaia** [comment]
Me too.

**Comment by linlih** [comment]
I pull a request to update the image url #24

**Comment by vasanthk** [comment]
@linlih Thank you for the PR and fixing this.
